config/routes.rb
Rails.application.routes.draw do
  resources :queries
  root 'queries#index'

end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
        if user.role == 'admin'
            can :manage, :all
        else
            can :read, :all
        end
    end
end

app/models/cffex.rb
class Cffex < ActiveRecord::Base
end

app/models/cffex_hft.rb
class CffexHft < ActiveRecord::Base
end

app/models/czce.rb
class Czce < ActiveRecord::Base
  # default_scope  do
  #   exclude_columns = %w(created_at updated_at product_type open_interest trade_volume)
  #   filtered_cols = (column_names - exclude_columns.map(&:to_s)).map{|i| "czces."+i}
  #   self.select(filtered_cols)
  # end



  def self.raw_query(begin_time, end_time)
    raw_q = 'SELECT cast(ticktime as timestamp(1)) AS ticktime
              ,max(bid_price) as price, max(bid_volume) as volume
              From  czces
              WHERE ticktime >= \"#{begin_time}\"::timestamp
              AND  ticktime <  \"#{end_time}\"::timestamp
              AND  (product_type =\'RS\')
              Group BY 1
              ORDER BY ticktime DESC
              limit 10000;'
    ActiveRecord::Base.connection.select_all(raw_q)
  end
end

app/models/czce_hft.rb
class CzceHft < ActiveRecord::Base
end

app/models/data_source.rb
class DataSource < ActiveRecord::Base
end

app/models/query.rb
class Query < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/datetime_helper.rb
module DatetimeHelper
  extend ActiveSupport::Concern
  def get_delta_time
    quantity = q[:delta_time].scan(/\d+/).first.to_i
    time_unit =  q[:delta_time].scan(/\D+/).first.strip
    unless ["second", "minute", "hour", "day", "week", "month", "year"].include? time_unit
      @errors << "Wrong time_unit"
      return false       
    end
    return "#{quantity}.#{time_unit}"
  end
end

app/controllers/concerns/queryable.rb
module Queryable
  extend ActiveSupport::Concern
    # binding.pry
    # q_str = query_str(params["sample_freq"], params["begin_time"], params["end_time"], params["product_type"])
  attr_accessor :errors , :query_type , :q
  errors = []

  def get_query_result
    filter_params
    check_params
    normalize_params
    print_query_log
    ActiveRecord::Base.connection.execute(build_query)
  end

  def filter_params
    self.q = params.clone
    q.delete("controller")
    q.delete("action")
  end

  def check_params # specified has higher priority than relative
    specified = ["market", "product", "contract_month", "frequency", "start_dt", "end_dt"]
    relative = ["market", "product", "contract_month", "frequency", "event_dt", "delta_time"]
    if 0 == (specified - q.keys).count
      self.query_type = :specified
    elsif 0 == (relative - q.keys).count 
      self.query_type = :relative  
    else
      self.query_type = :none
      @errors <<  "The correct parameters should be #{specified} or #{relative}"
    end
  end

  def normalize_params
    if :relative == query_type
      delta_time = get_delta_time
      q[:start_dt] = q[:event_dt]
      q[:end_dt] = (Date.parse(q[:start_dt]) + eval(delta_time)).strftime('%Y-%m-%d %H:%M:%S')
      q.delete(:event_dt)
      q.delete(:delta_time)
    end
  end

  def print_query_log
    ap("http://#{request.env["HTTP_HOST"]}/?"+URI::unescape(q.to_query))
    print "\n\n"
  end


  def build_query
    %{
      SELECT DISTINCT ON (time)
        time, high, low, open, close, volume
        FROM #{q[:market]} WHERE product_type = '#{q[:product]}'
        AND frequence = '#{q[:frequency]}'
        AND contract_month = '#{q[:contract_month]}'
        AND time >= '#{q[:start_dt]}'
        AND time < '#{q[:end_dt]}' 
    }.gsub(/\s+/, " ").strip
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show, :edit, :update, :destroy]
  include QueriesHelper
  include Queryable
  include DatetimeHelper

  respond_to :json

  def index
    @errors = []
    begin
      render json: Oj.dump(get_query_result.to_a, mode: :compat)
    rescue Exception => e
      render json: { :errors => "#{e.to_s}" }
    end
  end

  def show
    respond_with(@query)
  end

  def new
    @query = Query.new
    respond_with(@query)
  end

  def edit
  end

  def create
    @query = Query.new(query_params)
    @query.save
    respond_with(@query)
  end

  def update
    @query.update(query_params)
    respond_with(@query)
  end

  def destroy
    @query.destroy
    respond_with(@query)
  end

  private
    def set_query
      @query = Query.find(params[:id])
    end

    def query_params
      params.require(:query).permit(:user_id, :query_content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    #    Returns the full title on a per-page basis.
    def full_title(page_title)
        base_title = "Website sandbox"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end

end

app/helpers/queries_helper.rb
module QueriesHelper

  def query_str(interval, begin_time, end_time, product_type)
      %{SELECT date_trunc(\'#{interval}\', ticktime) AS ticktime_stamp,
            max(bid_price) as high,
            min(bid_price) as low,
            sum(bid_volume) as volume,
            max(product_type) as product_type
            FROM   czces
            WHERE  ticktime >=  \'#{begin_time}\'::timestamp
            AND  ticktime <  \'#{end_time}\'::timestamp
            AND  product_type =\'#{product_type}\'
            GROUP  BY 1
            ORDER  BY ticktime_stamp ASC;
        }.gsub(/\s+/, " ").strip

%{
  SELECT DISTINCT ON (1)
       date_trunc('#{interval}', ticktime) AS ticktime_stamp
     , max(bid_price)         OVER w AS high
     , min(bid_price)         OVER w AS low
     , sum(bid_volume)        OVER w AS volume
     , max(product_type)      OVER w AS product_type
     , min(product_type)      OVER w AS product_type
     , first_value(bid_price) OVER w AS open
     , lAst_value(bid_price)  OVER w AS close
    FROM   czces
    WHERE  ticktime >= '#{begin_time}'::timestamp
    AND    ticktime <  '#{end_time}'::timestamp
    AND    product_type ='#{product_type}'
    WINDOW w AS (PARTITION BY date_trunc('#{interval}', ticktime) ORDER BY ticktime
                 ROWS BETWEEN UNBOUNDED PRECEDING
                          AND UNBOUNDED FOLLOWING)
    ORDER  BY 1

    ;

}.gsub(/\s+/, " ").strip

  end

  def check_product_type_and_sample_freq
    ["CF", "ME", "RI", "PM", "RS", "WH", "RM", "OI", "TC", "TA", "FG", "JR", "SR"]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CnMarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/queries/_form.html.haml
= form_for @query do |f|
  - if @query.errors.any?
    #error_explanation
      %h2= "#{pluralize(@query.errors.count, "error")} prohibited this query from being saved:"
      %ul
        - @query.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :query_content
    = f.text_area :query_content
  .actions
    = f.submit 'Save'

app/views/queries/edit.html.haml
%h1 Editing query

= render 'form'

= link_to 'Show', @query
\|
= link_to 'Back', queries_path

app/views/queries/index.html.haml
%h1 Listing queries

%table
  %thead
    %tr
      %th User
      %th Query content
      %th
      %th
      %th
      
  %tbody
    - @queries.each do |query|
      %tr
        %td= query.user_id
        %td= query.query_content
        %td= link_to 'Show', query
        %td= link_to 'Edit', edit_query_path(query)
        %td= link_to 'Destroy', query, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Query', new_query_path

app/views/queries/new.html.haml
%h1 New query

= render 'form'

= link_to 'Back', queries_path

app/views/queries/show.html.haml
%p#notice= notice

%p
  %b User:
  = @query.user_id
%p
  %b Query content:
  = @query.query_content

= link_to 'Edit', edit_query_path(@query)
\|
= link_to 'Back', queries_path